apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::551210489378:role/eksctl-brain-tasks-app-cluster-nod-NodeInstanceRole-7h4DiRpoRHBw
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::551210489378:role/service-role/codebuild-brain-tasks-app-service-role
      username: codebuild-user
      groups:
        - system:masters

    - rolearn: arn:aws:iam::551210489378:role/CodeDeployEC2Role
      username: codedeploy-user
      groups:
        - system:masters
