version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl and aws-iam-authenticator..."
      - curl -o kubectl https://amazon-eks.s3.ap-south-1.amazonaws.com/1.29.0/2024-06-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
      - curl -o aws-iam-authenticator https://amazon-eks.s3.ap-south-1.amazonaws.com/1.29.0/2024-06-12/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mv ./aws-iam-authenticator /usr/local/bin/
      - echo "Installed tools successfully."

  pre_build:
    commands:
      - echo "Logging into EKS..."
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-app-cluster
      - echo "Kubeconfig setup complete."

  build:
    commands:
      - echo "Running build steps..."

  post_build:
    commands:
      - echo "--- Applying Kubernetes deployment ---"
      - kubectl apply -f k8s/deployment.yaml

artifacts:
  files:
    - '**/*'

