version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl and aws-iam-authenticator..."
      - curl -LO --fail "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" || echo "Failed to download kubectl...Retry...."
      - file kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - curl -LO --fail "https://amazon-eks.s3.us-west-2.amazonaws.com/1.29.0/2024-06-12/bin/linux/amd64/aws-iam-authenticator" || echo "Failed to download aws-iam-authenticator..Retry"
      - file aws-iam-authenticator
      - chmod +x aws-iam-authenticator
      - mv aws-iam-authenticator /usr/local/bin/
      - echo "#################Verifying the installation.."
      - kubectl version --client
      - aws-iam-authenticator help

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 551210489378.dkr.ecr.ap-south-1.amazonaws.com

      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - export IMAGE_TAG=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t brain-tasks-app:$IMAGE_TAG .
      - docker tag brain-tasks-app:$IMAGE_TAG 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG
      - echo "Writing image tag to deployment.yaml..."
      - 'sed -i "s|image:.*|image: 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG|" k8s/deployment.yaml'
      - echo "Deploying to EKS..."
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-app-cluster

      - echo "--- DEBUG:deployment.yaml content ---"
      - cat k8s/deployment.yaml
      - echo "--- DEBUG:current kubectl context ---"
      - kubectl config current-context
      - echo "--- DEBUG:cluster info ---"
      - kubectl cluster-info

      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml

artifacts:
  files:
    - '**/*'
