version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 551210489378.dkr.ecr.ap-south-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - docker build -t brain-tasks-app:$IMAGE_TAG .
      - docker tag brain-tasks-app:$IMAGE_TAG 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG
      - echo Writing image tag to deployment.yaml...
      - sed -i "s|image:.*|image: 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG|" k8s/deployment.yaml
      - echo Deploying to EKS...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-app-cluster
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml

artifacts:
  files:
    - '**/*'

