version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl and aws-iam-authenticator..."
      - curl -LO --fail "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" || echo "Failed to download kubectl...Retry...."
      - file kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo "#################Verifying the installation.."
      - kubectl version --client

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 551210489378.dkr.ecr.ap-south-1.amazonaws.com

      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - export IMAGE_TAG=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t brain-tasks-app:$IMAGE_TAG .
      - docker tag brain-tasks-app:$IMAGE_TAG 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG

  post_build:
    commands:
      - echo "###Debug Message-006:Pushing the Docker image..."
      - docker push 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG

      - echo "###Debug Message-007:Writing image tag to deployment.yaml..."
      - 'sed -i "s|image:.*|image: 551210489378.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG|" k8s/deployment.yaml'

      - echo "###Debug Message-008:Deploying to EKS..."
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-app-cluster --kubeconfig /root/.kube/config

      - echo "###Debug Message-012:Kubeconfig view print the contents of the kubeconfig file. Check correct EKS cluster context and AWS IAM credentials shown below"
      - kubectl config view

      - echo "###Debug Message-009:deployment.yaml content ---"
      - cat k8s/deployment.yaml

      - echo "###Debug Message-010:current kubectl context ---"
      - kubectl config current-context

      - echo "###Debug Message-013:Print out the AWS account and IAM role in use by CodeBuild"
      - aws sts get-caller-identity

      - echo "###Debug Message-011:cluster info and dump details ---"
#      - kubectl cluster-info
#      - kubectl cluster-info dump

      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml

artifacts:
  files:
    - '**/*'
