apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: ClusterIP
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
