apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  type: ClusterIP
  selector:
    app: brain-tasks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
