apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-app-service
spec:
  selector:
    app: brain-tasks-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

